// ──────────────────────────────────────────────────────────────────────────
//  SDF 3D Texture — GLSL usage snippet
//  Generated by the Blender SDF 3D Texture Generator addon
// ──────────────────────────────────────────────────────────────────────────

// --- Uniforms (set from your application) ---------------------------------
uniform sampler3D u_sdf;
// Tip: bind with GL_LINEAR for smooth density; GL_NEAREST for crisp edges.

// World-space AABB baked into this SDF
const vec3 SDF_BOUNDS_MIN = vec3(-0.525884, -0.530691, -0.150658);
const vec3 SDF_BOUNDS_MAX = vec3(0.423126, 0.383469, 1.284077);

// --- Helper: sample SDF at a world-space position -------------------------
float sampleSDF(vec3 worldPos) {
    vec3 uvw = (worldPos - SDF_BOUNDS_MIN)
             / (SDF_BOUNDS_MAX - SDF_BOUNDS_MIN);
    // Optional: return a large positive distance outside the bbox
    if (any(lessThan(uvw, vec3(0.0))) || any(greaterThan(uvw, vec3(1.0))))
        return 1.0;
    return texture(u_sdf, uvw).r;
}

// --- Basic cloud density from SDF ----------------------------------------
//  sdf < 0 → inside shape → density > 0
//  sdf > 0 → outside      → density = 0
float cloudDensity(vec3 worldPos) {
    float sdf = sampleSDF(worldPos);
    return max(0.0, -sdf);
}

// --- Soft density with a feathered edge ----------------------------------
//  feather: distance over which the edge fades (world units)
float cloudDensitySoft(vec3 worldPos, float feather) {
    float sdf = sampleSDF(worldPos);
    return 1.0 - smoothstep(-feather, feather, sdf);
}

// --- Approximate surface normal from SDF gradient (central differences) --
vec3 sdfGradient(vec3 worldPos) {
    float span = (SDF_BOUNDS_MAX.x - SDF_BOUNDS_MIN.x);
    float e    = span * 0.004;                // small offset (~0.4 % of box)
    float dx = sampleSDF(worldPos + vec3(e, 0, 0))
             - sampleSDF(worldPos - vec3(e, 0, 0));
    float dy = sampleSDF(worldPos + vec3(0, e, 0))
             - sampleSDF(worldPos - vec3(0, e, 0));
    float dz = sampleSDF(worldPos + vec3(0, 0, e))
             - sampleSDF(worldPos - vec3(0, 0, e));
    return normalize(vec3(dx, dy, dz));
}

// --- Ray-march skeleton for volumetric cloud (simplified) ----------------
//
//  Call this from your fragment or compute shader.
//
//  rayOrigin, rayDir   : camera ray in world space
//  tMin, tMax          : ray enter/exit distance
//  numSteps            : march quality (64–256)
//  absorption          : controls opacity build-up
//  Returns: vec4(RGB colour, transmittance)  — composite over background
//
vec4 raymarchCloud(
    vec3  rayOrigin,
    vec3  rayDir,
    float tMin,
    float tMax,
    int   numSteps,
    float absorption
) {
    float stepSize    = (tMax - tMin) / float(numSteps);
    float transmit    = 1.0;
    vec3  accumulated = vec3(0.0);

    for (int i = 0; i < numSteps; ++i) {
        float t   = tMin + (float(i) + 0.5) * stepSize;
        vec3  pos = rayOrigin + t * rayDir;

        float density = cloudDensitySoft(pos, 0.05);
        if (density < 0.001) continue;

        // Simple single-scattering colour (replace with your lighting)
        vec3 cloudColour = vec3(1.0, 0.98, 0.96);

        float alpha   = 1.0 - exp(-absorption * density * stepSize);
        accumulated  += transmit * alpha * cloudColour;
        transmit     *= 1.0 - alpha;

        if (transmit < 0.01) break;   // early out — fully opaque
    }

    return vec4(accumulated, 1.0 - transmit);
}

// --- Application-side OpenGL upload (C++ pseudo-code) --------------------
//
//  FILE *f = fopen("output.raw", "rb");
//  fread(data, sizeof(float), RX * RY * RZ, f);
//
//  GLuint tex;
//  glGenTextures(1, &tex);
//  glBindTexture(GL_TEXTURE_3D, tex);
//  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MIN_FILTER, GL_LINEAR);
//  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_MAG_FILTER, GL_LINEAR);
//  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_S, GL_CLAMP_TO_EDGE);
//  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_T, GL_CLAMP_TO_EDGE);
//  glTexParameteri(GL_TEXTURE_3D, GL_TEXTURE_WRAP_R, GL_CLAMP_TO_EDGE);
//  glTexImage3D(GL_TEXTURE_3D, 0, GL_R32F,
//               RX, RY, RZ, 0, GL_RED, GL_FLOAT, data);
//
// ──────────────────────────────────────────────────────────────────────────
